services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azure-blob-storage-emulator
    restart: unless-stopped
    command: azurite-blob --loose --blobHost 0.0.0.0 --blobPort 10000 --location /data
    ports:
      - "10000:10000" 
    volumes:
      - azurite-data:/data
  db:
    image: postgres:16-alpine
    container_name: cez-student-assistant-db
    environment:
      - POSTGRES_DB=CezStudentAssistantDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
        - "5432:5432"
volumes:
  postgres_data:
  azurite-data: