using CezStudentAssistant.API;
using CezStudentAssistant.Application.Dtos.Cez;
using CezStudentAssistant.Application.Interfaces.External;
using CezStudentAssistant.Application.Interfaces.Services;
using CezStudentAssistant.Application.Responses.Cez;
using CezStudentAssistant.Application.Requests.Cez;
using CezStudentAssistant.Infrastructure.Persistence.Data;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using NSubstitute;
using Testcontainers.PostgreSql;
using DotNet.Testcontainers.Containers;
using DotNet.Testcontainers.Builders;
using Azure.Storage.Blobs;
using NUnit.Framework;

[assembly: NonParallelizable]

namespace CezStudentAssistant.IntegrationTests;

public class CustomWebApplicationFactory : WebApplicationFactory<Program>
{
    private static readonly PostgreSqlContainer DatabaseContainer = new PostgreSqlBuilder("postgres:17-alpine")
        .WithDatabase("cezstudentassistant_integration_tests")
        .WithUsername("postgres")
        .WithPassword("postgres")
        .Build();

    private static readonly IContainer BlobContainer = new ContainerBuilder()
        .WithImage("mcr.microsoft.com/azure-storage/azurite:3.33.0")
        .WithPortBinding(10000, true)
        .WithCommand("azurite-blob", "--blobHost", "0.0.0.0", "--skipApiVersionCheck")
        .Build();

    static CustomWebApplicationFactory()
    {
        DatabaseContainer.StartAsync().GetAwaiter().GetResult();
        BlobContainer.StartAsync().GetAwaiter().GetResult();
        Environment.SetEnvironmentVariable("ConnectionStrings__DefaultConnection", DatabaseContainer.GetConnectionString());

        var blobConnectionString = $"DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://{BlobContainer.Hostname}:{BlobContainer.GetMappedPublicPort(10000)}/devstoreaccount1;";
        Environment.SetEnvironmentVariable("ConnectionStrings__AzureBlobStorage", blobConnectionString);

        Environment.SetEnvironmentVariable("Cez__ApiBaseUrl", "https://cez.test/");
    }

    public ICezApiClient CezApiClientMock { get; } = Substitute.For<ICezApiClient>();
    public IAIClient AIClientMock { get; } = Substitute.For<IAIClient>();
    public static IReadOnlyList<CezCourse> DefaultCezCourses { get; } = new List<CezCourse>
    {
        new() { ExternalId = 101, DisplayName = "Calculus I" },
        new() { ExternalId = 102, DisplayName = "Physics II" }
    };

    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        builder.UseEnvironment("Development");

        CezApiClientMock.GetUserCourses(Arg.Any<CezUserRequest>())
            .Returns(new CezGetUserCoursesResponse
            {
                Success = true,
                Data = DefaultCezCourses.ToList()
            });

        CezApiClientMock.GetCourseContent(Arg.Any<CezCourseRequest>())
            .Returns(new CezCourseContentResponse
            {
                Success = true,
                Data = new List<CezCourseContent>()
            });

        AIClientMock.GenerateQuizAsync(Arg.Any<CezStudentAssistant.Application.Requests.AI.AIQuizRequest>())
            .Returns(callInfo =>
            {
                var req = callInfo.Arg<CezStudentAssistant.Application.Requests.AI.AIQuizRequest>();
                if (req.AdditionalInstructions == "hard")
                {
                    return Task.FromResult(new CezStudentAssistant.Application.Responses.AI.Quiz.AIQuizResponse
                    {
                        Success = false,
                        Message = "AI model overloaded"
                    });
                }
                return Task.FromResult(new CezStudentAssistant.Application.Responses.AI.Quiz.AIQuizResponse
                {
                    Success = true,
                    Data = new CezStudentAssistant.Application.Responses.AI.Quiz.AIQuiz
                    {
                        Title = "AI Math Quiz",
                        Description = "A quiz generated by AI integration tests",
                        Questions = new List<CezStudentAssistant.Application.Responses.AI.Quiz.AIQuestion>
                        {
                            new CezStudentAssistant.Application.Responses.AI.Quiz.AIQuestion
                            {
                                Content = "What is 2+2?",
                                QuestionType = CezStudentAssistant.Domain.Enums.QuestionType.SingleChoice,
                                Difficulty = CezStudentAssistant.Domain.Enums.QuestionDifficulty.Easy,
                                Options = new List<CezStudentAssistant.Application.Responses.AI.Quiz.AIQuestionOption>
                                {
                                    new CezStudentAssistant.Application.Responses.AI.Quiz.AIQuestionOption { Content = "4", IsCorrect = true },
                                    new CezStudentAssistant.Application.Responses.AI.Quiz.AIQuestionOption { Content = "5", IsCorrect = false }
                                }
                            }
                        }
                    }
                });
            });

        AIClientMock.EstimateTokenUsageAsync(Arg.Any<CezStudentAssistant.Application.Requests.AI.AIQuizRequest>())
            .Returns(Task.FromResult(500));

        builder.ConfigureServices(services =>
        {
            // Mock External CEZ API and AI Client
            services.AddSingleton(CezApiClientMock);
            services.AddSingleton(AIClientMock);
            services.AddScoped<IJobScheduler, ScopedImmediateJobScheduler>();
        });
    }

    public void ResetDatabase()
    {
        using var scope = Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        db.Database.EnsureDeleted();
        db.Database.Migrate();

        var blobServiceClient = scope.ServiceProvider.GetRequiredService<BlobServiceClient>();
        var containerClient = blobServiceClient.GetBlobContainerClient("course-files");
        containerClient.CreateIfNotExists();
    }
}
