name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  backend:
    name: .NET
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x' 

    - name: Restore dependencies
      run: dotnet restore CezStudentAssistant.slnx

    - name: Build
      run: dotnet build --no-restore OcenaPracownicza.slnx

    - name: Test
      run: dotnet test OcenaPracownicza.slnx
  frontend:
    name: React
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install
      working-directory: ./src/cez-student-assistant-app

    - name: Build
      run: npm run build
      working-directory: ./src/cez-student-assistant-app
